// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbeS-uMmXeB7x8RUhqvhNojMLv0eFKjG0',
    appId: '1:380092191332:web:be2d362e6797e4c8180571',
    messagingSenderId: '380092191332',
    projectId: 'mcargo-ba218',
    authDomain: 'mcargo-ba218.firebaseapp.com',
    storageBucket: 'mcargo-ba218.appspot.com',
    measurementId: 'G-YZR1NZ3EP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3vlaC8YEDlDe6QsK88ICdFRd0lmGw60w',
    appId: '1:380092191332:android:3ee96addc0af0b31180571',
    messagingSenderId: '380092191332',
    projectId: 'mcargo-ba218',
    storageBucket: 'mcargo-ba218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANQgUZ2be7WsiJMfxQoN_Eu945HzOuQ7s',
    appId: '1:380092191332:ios:0d3eeeaf449c97e5180571',
    messagingSenderId: '380092191332',
    projectId: 'mcargo-ba218',
    storageBucket: 'mcargo-ba218.appspot.com',
    iosClientId: '380092191332-104u9un5j05o5mln0u4ofvv0jk79bmqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mCargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANQgUZ2be7WsiJMfxQoN_Eu945HzOuQ7s',
    appId: '1:380092191332:ios:0d3eeeaf449c97e5180571',
    messagingSenderId: '380092191332',
    projectId: 'mcargo-ba218',
    storageBucket: 'mcargo-ba218.appspot.com',
    iosClientId: '380092191332-104u9un5j05o5mln0u4ofvv0jk79bmqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mCargo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbeS-uMmXeB7x8RUhqvhNojMLv0eFKjG0',
    appId: '1:380092191332:web:3e346dc95090626b180571',
    messagingSenderId: '380092191332',
    projectId: 'mcargo-ba218',
    authDomain: 'mcargo-ba218.firebaseapp.com',
    storageBucket: 'mcargo-ba218.appspot.com',
    measurementId: 'G-EC0ECWRCCZ',
  );
}
